### ISSUE TITLE
Create Server

### ISSUE THREAD

**Issue by ginawatanabe** [HACC2016/surge#14]
Create express.js server 

references #5

**Comment by ghost** [comment]
I will implement handlebars.js templating engine via https://www.npmjs.com/package/hbs

**Comment by ghost** [comment]
Implemented handlebars through package called `hbs`. It's a package that wrapped Handlebars so that it works how Express server wants it to.

Pushed those changes to 7deba6e86e87d0f3dcc25ca12417709fb550e4c2 on saturday.

Next I will be converting the static HTML files in `app/` into templates and will be served by Express server. Expect these changes to land on the `feature/14-create-server` branch by Mid-day tomorrow at the latest.

**Comment by ghost** [comment]
Went with [Pug](https://pugjs.com) template engine.

Handlebars's setup and template inheritance was giving me a headache and Pug was faster to setup.

**Comment by ghost** [comment]
Merged `development` into `feature/14-create-server`

Any changes added to the HTML since last Saturday will need to be incorporated into the templating engine. @wata123 and I will work on this tonight via video chat before merging feature branch into `development`
